- roleId: 15
  roleName: "SupervisorFuel"
  actions:
    - getVehicleIdForCustomer
    - acceptPhonePayPayment
    - showHomePage
    - showPhonePePayments
    - submitCashtoVault
    - showSubmitCashtoVault
    - saveCollectPaymentSupervisorNew
    - saveCollectPaymentSupervisor
    - changePassword
    - showChangePassword
    - showCheckInScreen
    - showHomePage
    - checkInNozzle
    - showGenerateInvoice
    - checkOutNozzle
    - showCheckOutScreen
    - addTestFuel
    - showAddTestFuel
    - showUnclaimedPayments
    - showCollectPaymentSupervisor
    - showUserRoleMapping
    - showInvoiceConfig
    - showNozzleSelectionForm
    - showNozzleRegister
    - showPaytmTransctions
    - generateDailyPaymentRegister
    - showUserDetails
    - getAttendantsForDateAndShift
    - getAttendantsForDateAndShiftUnclubbed
    - exportNozzleRegister
  elements:
    - 700178
    - 700181
    - 700165
    - 700190
    - 700168
    - 21
    - 7
    - 700171
    - 700180
    - 700132
    - 700136
    - 700143
    - 700174
    - 26
    - 700195
    - 700197
