name: Database Backup Manual Trigger

on:
  workflow_dispatch:  # Allows manual trigger only

jobs:
  backup-database:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Increased timeout to 6 hours

    steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.UBUNTU_PRIVATE_KEY }}

    - name: Set SSH Keep-Alive Options
      run: echo -e "Host *\n  ServerAliveInterval 60\n  ServerAliveCountMax 240" >> ~/.ssh/config

    - name: SSH into Ubuntu machine, shutdown Apache Tomcat, restart MySQL, and run Go database backup
      run: |
        ssh -o StrictHostKeyChecking=no -p 22 ubuntu@hisaabcloud.in "
          # Base backup directory
          BACKUP_DIR='/home/ubuntu/mysqlbackup'

          # Define date-based subdirectory (e.g., 2024-11-13)
          DATE_DIR=\$(date +'%Y-%m-%d')
          TIMESTAMP=\$(date +'%Y-%m-%d_%H-%M-%S')

          # Full backup directory path (base + date)
          FULL_BACKUP_DIR=\$BACKUP_DIR/\$DATE_DIR
          
          # Create the date-based directory
          echo \$(date +'%Y-%m-%d %H:%M:%S') ' - Creating backup directory: '\$FULL_BACKUP_DIR
          mkdir -p \$FULL_BACKUP_DIR

          # Shutdown Apache Tomcat
          echo \$(date +'%Y-%m-%d %H:%M:%S') ' - Shutting down Apache Tomcat'
          sudo ./apache-tomcat-9.0.85/bin/shutdown.sh

          # Restart MySQL service to ensure a clean state
          echo \$(date +'%Y-%
