name: Database Backup Daily at 10 PM IST

on:
  schedule:
    - cron: '30 16 * * *'  # This runs the job every day at 16:30 UTC (22:00 IST)

jobs:
  backup-database:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.UBUNTU_PRIVATE_KEY }}

    - name: SSH into Ubuntu machine, shutdown Apache Tomcat, restart MySQL, and run Go database backup
      run: |
        ssh -o StrictHostKeyChecking=no -p 22 ubuntu@hisaabcloud.in "
          # Shutdown Apache Tomcat
          sudo ./apache-tomcat-9.0.85/bin/shutdown.sh

          # Restart MySQL service to ensure a clean state
          sudo service mysql restart

          # Define the backup directory and timestamp
          BACKUP_DIR='/home/ubuntu/mysqlbackup'
          TIMESTAMP=\$(date +'%Y-%m-%d_%H-%M-%S')

          # Ensure the mysqlbackup directory exists
          mkdir -p \$BACKUP_DIR

          # Run the Go program to take the backup for all specified databases
          \$BACKUP_DIR/mysqldump-arm64 -host=localhost -port=3306 -user=dbuser -password=${{ secrets.DB_PASSWORD }} \
          -databases=agserp,customizedpos,skpsecuritygate,sme,society_maintenance,ssegpl \
          -exclude=mst_users

          # Move the compressed backups to the mysqlbackup directory with timestamp
          mv agserp.7z \$BACKUP_DIR/agserp_\$TIMESTAMP.7z
          mv customizedpos.7z \$BACKUP_DIR/customizedpos_\$TIMESTAMP.7z
          mv skpsecuritygate.7z \$BACKUP_DIR/skpsecuritygate_\$TIMESTAMP.7z
          mv sme.7z \$BACKUP_DIR/sme_\$TIMESTAMP.7z
          mv society_maintenance.7z \$BACKUP_DIR/society_maintenance_\$TIMESTAMP.7z
          mv ssegpl.7z \$BACKUP_DIR/ssegpl_\$TIMESTAMP.7z

          # Start Apache Tomcat again after the backup is done
          sudo ./apache-tomcat-9.0.85/bin/startup.sh
        "
