name: Database Backup Scheduled Trigger

on:
  schedule:
    - cron: "30 17 * * *"  # Triggers daily at 17:30 UTC, which is 23:00 IST

jobs:
  backup-database:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Increased timeout to 6 hours

    steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.UBUNTU_PRIVATE_KEY }}

    - name: Set SSH Keep-Alive Options
      run: echo -e "Host *\n  ServerAliveInterval 60\n  ServerAliveCountMax 240" >> ~/.ssh/config

    - name: SSH into Ubuntu machine, shutdown Apache Tomcat, restart MySQL, and run Go database backup
      run: |
        ssh -o StrictHostKeyChecking=no -p 22 ubuntu@hisaabcloud.in "
          # Change to the backup directory at the start
          BACKUP_DIR='/home/ubuntu/mysqlbackup'
          cd \$BACKUP_DIR

          # Shutdown Apache Tomcat
          echo \$(date +'%Y-%m-%d %H:%M:%S') ' - Shutdown Apache Tomcat'
          sudo ./apache-tomcat-9.0.85/bin/shutdown.sh

          # Restart MySQL service to ensure a clean state
          echo \$(date +'%Y-%m-%d %H:%M:%S') ' - Restarting MySQL service'
          sudo service mysql restart

          # Ensure the backup directory exists
          echo \$(date +'%Y-%m-%d %H:%M:%S') ' - Ensuring backup directory exists'
          mkdir -p \$BACKUP_DIR

          # Define timestamp
          TIMESTAMP=\$(date +'%Y-%m-%d_%H-%M-%S')

          # Run the Go program to take the backup for all specified databases
          echo \$(date +'%Y-%m-%d %H:%M:%S') ' - Running Go backup program'
          \$BACKUP_DIR/mysqldump-arm64 -host=localhost -port=3306 -user=remotenuuser -password=${{ secrets.DB_PASSWORD }} \
          -databases=agserp,customizedpos,skpsecuritygate,sme,society_maintenance,ssegpl \
          -exclude=tbl_attachment_mst

          # Check if the dump was successful
          if [ -f \$BACKUP_DIR/agserp.7z ]; then
            echo \$(date +'%Y-%m-%d %H:%M:%S') ' - Dump created successfully'
          else
            echo \$(date +'%Y-%m-%d %H:%M:%S') ' - Error in creating dump'
            exit 1
          fi

          # Move the compressed backups to the mysqlbackup directory with timestamp
          echo \$(date +'%Y-%m-%d %H:%M:%S') ' - Moving backup files to timestamped filenames'
          mv \$BACKUP_DIR/agserp.7z \$BACKUP_DIR/agserp_\$TIMESTAMP.7z
          mv \$BACKUP_DIR/customizedpos.7z \$BACKUP_DIR/customizedpos_\$TIMESTAMP.7z
          mv \$BACKUP_DIR/skpsecuritygate.7z \$BACKUP_DIR/skpsecuritygate_\$TIMESTAMP.7z
          mv \$BACKUP_DIR/sme.7z \$BACKUP_DIR/sme_\$TIMESTAMP.7z
          mv \$BACKUP_DIR/society_maintenance.7z \$BACKUP_DIR/society_maintenance_\$TIMESTAMP.7z
          mv \$BACKUP_DIR/ssegpl.7z \$BACKUP_DIR/ssegpl_\$TIMESTAMP.7z

          # Start Apache Tomcat again after the backup is done
          echo \$(date +'%Y-%m-%d %H:%M:%S') ' - Starting Apache Tomcat again'
          cd ..
          sudo ./apache-tomcat-9.0.85/bin/startup.sh

          echo \$(date +'%Y-%m-%d %H:%M:%S') ' - Backup completed successfully!'
        "
